// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmT3bkjYXGVDjnp_6slztNydSeE2R5C18',
    appId: '1:1004132633284:web:58224c771b759e48c25791',
    messagingSenderId: '1004132633284',
    projectId: 'ecommerce-app-b7ef9',
    authDomain: 'ecommerce-app-b7ef9.firebaseapp.com',
    storageBucket: 'ecommerce-app-b7ef9.appspot.com',
    measurementId: 'G-ZX8M27MR23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCosq9-y4JGqLWOtC2PS9vvu4wblSrvHZU',
    appId: '1:388544869854:android:5e06d2041f8ef96eb0d94f',
    messagingSenderId: '388544869854',
    projectId: 'project-ff85d',
    storageBucket: 'project-ff85d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCollr0jMkwASUGzrv6uaN6TMDygvkyN_w',
    appId: '1:388544869854:web:160e57412855a603b0d94f',
    messagingSenderId: '388544869854',
    projectId: 'project-ff85d',
    authDomain: 'project-ff85d.firebaseapp.com',
    storageBucket: 'project-ff85d.appspot.com',
    measurementId: 'G-4P6XC4WTRC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS-MrLWfgKFfpRANZJ33KZn2BUt_pV4YE',
    appId: '1:388544869854:ios:dcd9ad92f487f111b0d94f',
    messagingSenderId: '388544869854',
    projectId: 'project-ff85d',
    storageBucket: 'project-ff85d.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

}