// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmT3bkjYXGVDjnp_6slztNydSeE2R5C18',
    appId: '1:1004132633284:web:58224c771b759e48c25791',
    messagingSenderId: '1004132633284',
    projectId: 'ecommerce-app-b7ef9',
    authDomain: 'ecommerce-app-b7ef9.firebaseapp.com',
    storageBucket: 'ecommerce-app-b7ef9.appspot.com',
    measurementId: 'G-ZX8M27MR23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFkx3zzRdktOcLL6X7991KZCTXzW3_mIA',
    appId: '1:1004132633284:android:597085e40b58ba4bc25791',
    messagingSenderId: '1004132633284',
    projectId: 'ecommerce-app-b7ef9',
    storageBucket: 'ecommerce-app-b7ef9.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmT3bkjYXGVDjnp_6slztNydSeE2R5C18',
    appId: '1:1004132633284:web:79c010965cd1bc38c25791',
    messagingSenderId: '1004132633284',
    projectId: 'ecommerce-app-b7ef9',
    authDomain: 'ecommerce-app-b7ef9.firebaseapp.com',
    storageBucket: 'ecommerce-app-b7ef9.appspot.com',
    measurementId: 'G-XTY0LE8K1C',
  );
}
